### ISSUE TITLE
Компоненты

### ISSUE THREAD

**Issue by arhangelsoft** [CHERTS/mspeech#1]
Если уж нет исходников, то и распространяли бы бинарники сразу под все версии IDE (под которые можете собирать).

**Comment by arhangelsoft** [comment]
А можете собрать DCU для XE 10?

**Comment by cherts** [comment]
Чтобы распространять бинарники под все RAD Studio нужно вначале их купить, а это стоит огромных денег.
Под XE 10 к сожалению не могу собрать, нет этой версии.

**Comment by cherts** [comment]
Вообще говоря, я готов выложить полные исходники MGSoft, как только кто-нибудь купить их хотя бы 1 раз, это 8 компонентов по 1 т.р. за каждый, то есть 8 т.р. или $120. Это скромная сумма за потраченное мной 2 года назад время на написание этих компонентов. Но т.к. я не рекламирую эти исходники нигде, покупать их никто и не покупает и поэтому код я и не выкладываю.
