### ISSUE TITLE
программе требуются права уровня админа

### ISSUE THREAD

**Issue by AnotherAnkor** [CHERTS/mspeech#2]
для выполнения скриптов программе потребуются права уровня админа. Обычный пользователь вроде как не может выключить машину из командной строки.

**Comment by cherts** [comment]
Кто Вам сказал, что для shutdown /s требуются права Администратора?

**Comment by AnotherAnkor** [comment]
Я мог и ошибиться. Но для большинства системных вызовов они таки требуются.
Тестировали без прав админа?

2016-05-20 15:55 GMT+03:00 Mikhail Grigorev notifications@github.com:

> Кто Вам сказал, что для shutdown /s требуются права Администратора?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/CHERTS/mspeech/issues/2#issuecomment-220597857

## 

С уважением, Андрей Михайлович Корниенко.

**Comment by cherts** [comment]
Зачем тестировать, я каждый день это делаю, давая команду ВЫКЛЮЧИ КОМПЬЮТЕР и работаю при этом с правами обычного пользователя.
