### ISSUE TITLE
Google, Yandex API и т.д.

### ISSUE THREAD

**Issue by MVoz** [CHERTS/mspeech#3]
спасибо за разработку
хотелось бы увидеть в ридми текст, как получить ключи на доступ к API к тем ресурсам которые обозначены в данном приложение

п.с. сам то нагуглю, но ... многие даже незнают что такое API и ключи

**Comment by cherts** [comment]
Для тех кто не знает, что такое API и т.п., есть бинарная сборка MSpeech, где все работает из коробки и не нужны ключи.
Там же в MSpeech есть ссылка на ресурс где получить ключ, только сейчас это сделать нельзя, Google  перестал выдавать ключи к Speech API за бесплатно. Но старые ключи продолжают работать.
